/**
 * PARKED / disabled — golden-table regression oracle for container-lifecycle.
 *
 * Why parked: transition() is already exhaustively verified by the .oracle
 * Python differential (.oracle/tests/test_container_lifecycle.py, 299 cells
 * NRI-vs-TS). This in-repo golden is a second copy of the same check; judged
 * low marginal value vs its upkeep, so it's kept off for now. See ISSUE-00057.
 *
 * To re-enable: uncomment the body below, remove the describe.skip stub, and
 * regenerate the data with `python .oracle/scripts/generate_golden.py`
 * (writes tests/oracle/container-lifecycle.golden.json).
 *
 * The stub below keeps vitest happy — a fully-commented file errors with
 * "No test suite found".
 */
import { describe, it } from 'vitest';
describe.skip('golden regression — PARKED (see file header)', () => {
  it('parked', () => {});
});

// /**
//  * Golden answer table vitest — freeze container-lifecycle transition table
//  * against the NRI (Naive Reference Implementation).
//  *
//  * Loads golden.json (generated by .oracle/scripts/generate_golden.py)
//  * and asserts every (state, trigger) pair matches the TypeScript transition().
//  *
//  * This is a REGRESSION oracle: if the TS implementation diverges from the
//  * NRI model, this test catches it.  The golden file is version-controlled.
//  */
// import { describe, it, expect } from 'vitest';
// import { transition, ContainerGroupState } from '../../src/core/provider/container-lifecycle.ts';
// import type { TransitionTrigger } from '../../src/core/provider/container-lifecycle.ts';
// import golden from './container-lifecycle.golden.json';

// interface GoldenEntry {
//   readonly state: string;
//   readonly trigger: TransitionTrigger;
//   readonly expected: string;
// }

// const entries = golden as GoldenEntry[];

// describe('NRI vs TS transition() — golden regression', () => {
//   for (const entry of entries) {
//     const triggerDesc =
//       entry.trigger.kind === 'System'
//         ? `System/${entry.trigger.event}`
//         : entry.trigger.kind === 'Api'
//           ? `Api/${entry.trigger.operation}`
//           : `RestartPolicy(exit=${entry.trigger.exitCode}, policy=${entry.trigger.policy})`;

//     it(`${entry.state} + ${triggerDesc} → ${entry.expected}`, () => {
//       const result = transition(
//         entry.state as ContainerGroupState,
//         entry.trigger as TransitionTrigger,
//       );
//       expect(result).toBe(entry.expected as ContainerGroupState);
//     });
//   }
// });
