// Auto-generated by scripts/generate-features.mjs
// Do not edit manually. Run `npm run generate` to update.

import { createRouter as infoRouter } from './info/index.ts';
import { createRouter as usersRouter } from './users/index.ts';
import { createRouter as permissionRouter } from './permission/index.ts';
import { createRouter as system_groupRouter } from './system-group/index.ts';
import { createRouter as templateRouter } from './template/index.ts';
import { createRouter as sandboxRouter } from './sandbox/index.ts';
import { createRouter as platformsRouter } from './platforms/index.ts';
import { createRouter as networkRouter } from './network/index.ts';
import { createRouter as topologyRouter } from './topology/index.ts';
import { createRouter as subnetRouter } from './subnet/index.ts';
import { createRouter as volumeRouter } from './volume/index.ts';
import { createRouter as container_secretRouter } from './container-secret/index.ts';
import { createRouter as imagesRouter } from './images/index.ts';
import { createRouter as actionsRouter } from './actions/index.ts';
import { createRouter as instancesRouter } from './instances/index.ts';

import type { FeatureDeps } from '../core/deps.ts';
import type { Hono } from 'hono';

export interface RegisteredFeature {
  path: string;
  mount: (deps: FeatureDeps) => Hono<any, any, any>;
}

export function getFeatures(): RegisteredFeature[] {
  return [
  { path: '/', mount: (deps) => infoRouter(deps) },
  { path: '/api/users', mount: (deps) => usersRouter(deps) },
  { path: '/api/permissions', mount: (deps) => permissionRouter(deps) },
  { path: '/api/system-groups', mount: (deps) => system_groupRouter(deps) },
  { path: '/api/templates', mount: (deps) => templateRouter(deps) },
  { path: '/api/sandboxes', mount: (deps) => sandboxRouter(deps) },
  { path: '/api/platforms', mount: (deps) => platformsRouter(deps) },
  { path: '/api/networks', mount: (deps) => networkRouter(deps) },
  { path: '/api/topology', mount: (deps) => topologyRouter(deps) },
  { path: '/api/subnets', mount: (deps) => subnetRouter(deps) },
  { path: '/api/volumes', mount: (deps) => volumeRouter(deps) },
  { path: '/api/container-secrets', mount: (deps) => container_secretRouter(deps) },
  { path: '/api/images', mount: (deps) => imagesRouter(deps) },
  { path: '/api/actions', mount: (deps) => actionsRouter(deps) },
  { path: '/api/instances', mount: (deps) => instancesRouter(deps) },  ];
}
