/**
 * Central error code registry — the single source of truth.
 *
 * Every handler and service must use these codes with fail() or AppError.
 * Adding a new code → add it here and to ERROR_HTTP_STATUS below.
 * Omitting the mapping entry → tsc error at compile time.
 *
 * Design: exhaustive const array → union type → Record mapping.
 * This ensures ERROR_HTTP_STATUS has exactly the same keys as the union.
 */

// ─── Generic errors (shared across resources) ───

export const GENERIC_ERROR_CODES = [
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'CONFLICT',
  'RATE_LIMITED',
  'INTERNAL_ERROR',
  'NOT_IMPLEMENTED',
  'SERVICE_UNAVAILABLE',
  'EXPIRED',
  'INVALID_REQUEST',
  'NOT_SUPPORTED',
] as const;

// ─── Resource-specific NOT_FOUND variants ───

export const NOT_FOUND_CODES = [
  'SANDBOX_NOT_FOUND',
  'VOLUME_NOT_FOUND',
  'SECRET_NOT_FOUND',
  'POLICY_NOT_FOUND',
  'USER_NOT_FOUND',
  'USERGROUP_NOT_FOUND',
  'PERMGROUP_NOT_FOUND',
  'ROUTEACL_NOT_FOUND',
  'USERTPL_NOT_FOUND',
  'TEMPLATE_NOT_FOUND',
  'RUNNER_NOT_FOUND',
  'RUNNER_GROUP_NOT_FOUND',
  'SYSGROUP_NOT_FOUND',
  'SUBNET_NOT_FOUND',
  'SECGROUP_NOT_FOUND',
  'INSTANCE_NOT_FOUND',
  'CREDENTIAL_NOT_FOUND',
  'BUCKET_NOT_FOUND',
  'IMAGE_NOT_FOUND',
  'PUBLIC_KEY_NOT_FOUND',
  'BLOB_NOT_FOUND',
  'STREAM_NOT_FOUND',
  'APPROVAL_NOT_FOUND',
  'INVITE_NOT_FOUND',
  'JOB_NOT_FOUND',
  'WORKFLOW_NOT_FOUND',
  'WORKSPACE_NOT_FOUND',
  'RUN_NOT_FOUND',
  'RUNTIME_NOT_FOUND',
  'GROUP_NOT_FOUND',
  'ORG_NOT_FOUND',
  'LINK_NOT_FOUND',
  'AVATAR_NOT_FOUND',
] as const;

// ─── Operation failures ───

export const OPERATION_ERROR_CODES = [
  'CREATE_FAILED',
  'UPDATE_FAILED',
  'DELETE_FAILED',
  'STOP_FAILED',
  'START_FAILED',
  'SYNC_FAILED',
  'RESTART_FAILED',
  'APPLY_FAILED',
  'HEARTBEAT_FAILED',
  'PULL_FAILED',
  'COMPLETE_FAILED',
  'UPLOAD_FAILED',
  'RESOLVE_ERROR',
] as const;

// ─── Provider errors ───

export const PROVIDER_ERROR_CODES = [
  'PROVIDER_ERROR',
  'PROVIDER_NOT_FOUND',
  'PROVIDER_UNREACHABLE',
  'PROVIDER_TIMEOUT',
  'PROVIDER_AUTH_FAILED',
  'PROVIDER_FORBIDDEN',
  'PROVIDER_QUOTA_EXCEEDED',
  'PROVIDER_ID_MISSING',
  'PROVIDER_RESOLUTION_FAILED',
  'PROVIDER_OPERATION_FAILED',
  'CREDENTIAL_RESOLUTION_FAILED',
  'NO_PROVIDER',
  'NO_CONTAINER',
  'LOGS_UNAVAILABLE',
] as const;

// ─── Resource-specific operational codes ───

export const RESOURCE_ERROR_CODES = [
  'INVALID_TRANSITION',
  'INVALID_STATUS',
  'INVALID_CIDR',
  'INVALID_ACTION',
  'INVALID_WORKFLOW',
  'INVALID_CREDENTIALS',
  'INVALID_PASSWORD',
  'INVALID_SECRET',
  'INVALID_CIPHERTEXT',
  'INVALID_MASTER_KEY',
  'INVALID_SIGNATURE',
  'INVALID_EXPIRY',
  'INSTANCE_HAS_SANDBOXES',
  'NOT_CONFIGURED',
  'NO_PUBLIC_KEY',
  'NOT_APPROVER',
  'NOT_HTTP_TRIGGER',
  'MAC_DENIED',
  'EMAIL_EXISTS',
  'LOGIN_DISABLED',
  'LOGIN_IP_RESTRICTED',
  'LOGIN_TIME_RESTRICTED',
  'PASSWORD_LOGIN_DISABLED',
  'PASSWORD_REQUIRED',
  'TOO_MANY_ATTEMPTS',
  'VERIFY_FAILED',
  'RESTART_NOT_ALLOWED',
  'RESTART_NOT_SUPPORTED',
  'START_NOT_SUPPORTED',
  'UPDATE_NOT_ALLOWED',
  'UPDATE_NOT_SUPPORTED',
  'ROUTEACL_DUPLICATE',
  'ALREADY_DECIDED',
  'ALREADY_PROCESSED',
  'REPLAY_DETECTED',
  'KEY_EXPIRED',
  'MISSING_ORG',
  'MISSING_SIGNATURE',
  'BAD_SIGNATURE',
  'BAD_TIMESTAMP',
  'BAD_KEY_FORMAT',
  'BAD_RATE_LIMIT_CONFIG',
  'UNSUPPORTED_DNS_TYPE',
  'LINK_DISABLED',
  'LINK_EXHAUSTED',
  'LINK_EXPIRED',
] as const;

// ─── Secret/blob specific codes ───

export const SECRET_ERROR_CODES = [
  'SECRET_EMPTY',
  'SECRET_NO_BLOB',
  'SECRET_BLOB_MISSING',
  'SECRET_INVALID_TYPE',
  'BLOB_STORE_UNAVAILABLE',
] as const;

// ─── Pod/sandbox specific codes ───

export const POD_ERROR_CODES = [
  'POD_CREATE_FAILED',
  'POD_LIST_FAILED',
  'POD_NOT_FOUND',
  'POD_GET_FAILED',
  'POD_STOP_FAILED',
  'POD_DELETE_FAILED',
  'POD_LOGS_FAILED',
  'POD_EXEC_FAILED',
  'POD_UPDATE_FAILED',
  'HEALTH_FAILED',
] as const;

// ─── Avatar specific codes ───

export const AVATAR_ERROR_CODES = [
  'AVATAR_TOO_LARGE',
  'AVATAR_EMPTY',
  'AVATAR_INVALID',
  'AVATAR_UNSUPPORTED_TYPE',
] as const;

// ═══════════════════════════════════════════════════════════════
// Union type — the single source of truth for all error codes
// ═══════════════════════════════════════════════════════════════

export const ALL_ERROR_CODES = [
  ...GENERIC_ERROR_CODES,
  ...NOT_FOUND_CODES,
  ...OPERATION_ERROR_CODES,
  ...PROVIDER_ERROR_CODES,
  ...RESOURCE_ERROR_CODES,
  ...SECRET_ERROR_CODES,
  ...POD_ERROR_CODES,
  ...AVATAR_ERROR_CODES,
  // Inline one-offs discovered by typecheck:
  'S3_POLICY_NOT_FOUND',
] as const;

export type ErrorCode = typeof ALL_ERROR_CODES[number];

// ═══════════════════════════════════════════════════════════════
// HTTP status mapping — compile-time enforced: omit any ErrorCode → tsc error
// ═══════════════════════════════════════════════════════════════

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  // Inline one-offs
  S3_POLICY_NOT_FOUND: 404,

  // Generic
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  SERVICE_UNAVAILABLE: 503,
  EXPIRED: 410,
  INVALID_REQUEST: 400,
  NOT_SUPPORTED: 400,

  // Not-found variants
  SANDBOX_NOT_FOUND: 404,
  VOLUME_NOT_FOUND: 404,
  SECRET_NOT_FOUND: 404,
  POLICY_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  USERGROUP_NOT_FOUND: 404,
  PERMGROUP_NOT_FOUND: 404,
  ROUTEACL_NOT_FOUND: 404,
  USERTPL_NOT_FOUND: 404,
  TEMPLATE_NOT_FOUND: 404,
  RUNNER_NOT_FOUND: 404,
  RUNNER_GROUP_NOT_FOUND: 404,
  SYSGROUP_NOT_FOUND: 404,
  SUBNET_NOT_FOUND: 404,
  SECGROUP_NOT_FOUND: 404,
  INSTANCE_NOT_FOUND: 404,
  CREDENTIAL_NOT_FOUND: 404,
  BUCKET_NOT_FOUND: 404,
  IMAGE_NOT_FOUND: 404,
  PUBLIC_KEY_NOT_FOUND: 404,
  BLOB_NOT_FOUND: 404,
  STREAM_NOT_FOUND: 404,
  APPROVAL_NOT_FOUND: 404,
  INVITE_NOT_FOUND: 404,
  JOB_NOT_FOUND: 404,
  WORKFLOW_NOT_FOUND: 404,
  WORKSPACE_NOT_FOUND: 404,
  RUN_NOT_FOUND: 404,
  RUNTIME_NOT_FOUND: 404,
  GROUP_NOT_FOUND: 404,
  ORG_NOT_FOUND: 404,
  LINK_NOT_FOUND: 404,
  AVATAR_NOT_FOUND: 404,

  // Operation failures
  CREATE_FAILED: 400,
  UPDATE_FAILED: 400,
  DELETE_FAILED: 400,
  STOP_FAILED: 400,
  START_FAILED: 400,
  SYNC_FAILED: 502,
  RESTART_FAILED: 409,
  APPLY_FAILED: 500,
  HEARTBEAT_FAILED: 400,
  PULL_FAILED: 502,
  COMPLETE_FAILED: 500,
  UPLOAD_FAILED: 500,
  RESOLVE_ERROR: 500,

  // Provider errors
  PROVIDER_ERROR: 502,
  PROVIDER_NOT_FOUND: 400,
  PROVIDER_UNREACHABLE: 502,
  PROVIDER_TIMEOUT: 504,
  PROVIDER_AUTH_FAILED: 401,
  PROVIDER_FORBIDDEN: 403,
  PROVIDER_QUOTA_EXCEEDED: 429,
  PROVIDER_ID_MISSING: 400,
  PROVIDER_RESOLUTION_FAILED: 503,
  PROVIDER_OPERATION_FAILED: 502,
  CREDENTIAL_RESOLUTION_FAILED: 401,
  NO_PROVIDER: 400,
  NO_CONTAINER: 400,
  LOGS_UNAVAILABLE: 502,

  // Resource-specific
  INVALID_TRANSITION: 409,
  INVALID_STATUS: 400,
  INVALID_CIDR: 400,
  INVALID_ACTION: 400,
  INVALID_WORKFLOW: 400,
  INVALID_CREDENTIALS: 401,
  INVALID_PASSWORD: 401,
  INVALID_SECRET: 400,
  INVALID_CIPHERTEXT: 400,
  INVALID_MASTER_KEY: 500,
  INVALID_SIGNATURE: 401,
  INVALID_EXPIRY: 400,
  INSTANCE_HAS_SANDBOXES: 409,
  NOT_CONFIGURED: 501,
  NO_PUBLIC_KEY: 404,
  NOT_APPROVER: 403,
  NOT_HTTP_TRIGGER: 400,
  MAC_DENIED: 403,
  EMAIL_EXISTS: 409,
  LOGIN_DISABLED: 403,
  LOGIN_IP_RESTRICTED: 403,
  LOGIN_TIME_RESTRICTED: 403,
  PASSWORD_LOGIN_DISABLED: 403,
  PASSWORD_REQUIRED: 400,
  TOO_MANY_ATTEMPTS: 429,
  VERIFY_FAILED: 401,
  RESTART_NOT_ALLOWED: 409,
  RESTART_NOT_SUPPORTED: 409,
  START_NOT_SUPPORTED: 501,
  UPDATE_NOT_ALLOWED: 403,
  UPDATE_NOT_SUPPORTED: 403,
  ROUTEACL_DUPLICATE: 409,
  ALREADY_DECIDED: 409,
  ALREADY_PROCESSED: 409,
  REPLAY_DETECTED: 409,
  KEY_EXPIRED: 410,
  MISSING_ORG: 400,
  MISSING_SIGNATURE: 401,
  BAD_SIGNATURE: 401,
  BAD_TIMESTAMP: 400,
  BAD_KEY_FORMAT: 400,
  BAD_RATE_LIMIT_CONFIG: 500,
  UNSUPPORTED_DNS_TYPE: 400,
  LINK_DISABLED: 403,
  LINK_EXHAUSTED: 429,
  LINK_EXPIRED: 410,

  // Secret/blob
  SECRET_EMPTY: 500,
  SECRET_NO_BLOB: 500,
  SECRET_BLOB_MISSING: 500,
  SECRET_INVALID_TYPE: 500,
  BLOB_STORE_UNAVAILABLE: 500,

  // Pod/sandbox
  POD_CREATE_FAILED: 500,
  POD_LIST_FAILED: 500,
  POD_NOT_FOUND: 404,
  POD_GET_FAILED: 500,
  POD_STOP_FAILED: 500,
  POD_DELETE_FAILED: 500,
  POD_LOGS_FAILED: 500,
  POD_EXEC_FAILED: 500,
  POD_UPDATE_FAILED: 409,
  HEALTH_FAILED: 500,

  // Avatar
  AVATAR_TOO_LARGE: 413,
  AVATAR_EMPTY: 400,
  AVATAR_INVALID: 415,
  AVATAR_UNSUPPORTED_TYPE: 415,
};
