import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createInfoHandler, infoRouteMeta } from '../src/features/info/info.handler.ts';
import type { RouteMeta } from '../src/core/http-docs/types.ts';

// ─── Route collector ───

interface RouteDoc {
  method: string;
  path: string;
  tag: string;
  meta?: RouteMeta;
}

const routes: RouteDoc[] = [];

function collect(
  label: string,
  app: ReturnType<typeof createInfoHandler>,
  metaList?: RouteMeta[],
) {
  for (const r of app.routes) {
    const method = r.method.toUpperCase();
    const path = r.path;
    const meta = metaList?.find(m => m.method === method && m.path === path);
    routes.push({ method, path, tag: label, meta });
  }
}

// ─── Register handlers ───

collect('Info', createInfoHandler(), infoRouteMeta);

// ─── Generate .http file ───

const __dirname = dirname(fileURLToPath(import.meta.url));
const httpDir = resolve(__dirname, '..', 'http');
mkdirSync(httpDir, { recursive: true });

const lines: string[] = [
  '### HBI-AAD API Endpoints',
  '### Auto-generated by scripts/export-http.ts — do not edit manually',
  '',
  '@baseUrl = http://localhost:3000',
  '',
];

let currentTag = '';
for (const route of routes) {
  if (route.tag !== currentTag) {
    currentTag = route.tag;
    lines.push('');
    lines.push(`# ─── ${route.tag} ───`);
    lines.push('');
  }

  const { method, path, meta } = route;

  // Description line
  lines.push(`### ${method} ${path}${meta?.description ? ` — ${meta.description}` : ''}`);

  // Response description comment
  if (meta?.responseDescription) {
    lines.push(`# Response: ${meta.responseDescription}`);
  }

  // Request line
  lines.push(`${method} {{baseUrl}}${path}`);

  // Request body for POST/PUT/PATCH
  if (meta?.requestBody && !['GET', 'DELETE'].includes(method)) {
    lines.push('Content-Type: application/json');
    lines.push('');
    lines.push(JSON.stringify(meta.requestBody, null, 2));
  }

  lines.push('');
}

// Deduplicate trailing blank lines
const content = lines.join('\n').replace(/\n{3,}/g, '\n\n');

writeFileSync(resolve(httpDir, 'api.http'), content, 'utf-8');
console.log(`✓ Generated ${httpDir}\\api.http (${routes.length} routes)`);
