import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createInfoHandler, infoRouteMeta } from '../src/features/info/info.handler.ts';
import { createUserRouter, userRouteMeta } from '../src/features/users/handler.ts';
import type { RouteMeta } from '../src/core/http-docs/types.ts';
import { createAuditRouter } from '../src/core/audit/audit-router.ts';
import { WorkersAuditLogger } from '../src/core/audit/workers-audit-logger.ts';

// ─── Route collector ───

interface RouteDoc {
  method: string;
  path: string;
  fileTag: string;
  tag: string;
  meta?: RouteMeta;
}

const routes: RouteDoc[] = [];

function collect(
  fileTag: string,
  label: string,
  basePath: string,
  app: ReturnType<typeof createInfoHandler | typeof createUserRouter | typeof createAuditRouter>,
  pathFilter: (relPath: string) => boolean,
  metaList?: RouteMeta[],
) {
  for (const r of app.routes) {
    const method = r.method.toUpperCase();
    const relPath = r.path;
    if (!pathFilter(relPath)) continue;
    const absPath = `${basePath}${relPath}`.replace(/\/+/g, '/');
    const meta = metaList?.find(m => m.method === method && m.path === relPath);
    routes.push({ method, path: absPath, fileTag, tag: label, meta });
  }
}

// ─── Audit route meta ───

const auditRouteMeta: RouteMeta[] = [
  {
    method: 'GET',
    path: '/logs',
    description: '查询审计日志（支持翻页，?page=&limit=）',
    responseDescription: '{ page, limit, total, totalPages, lines }',
  },
  {
    method: 'GET',
    path: '/logs/stats',
    description: '审计日志缓冲区统计',
    responseDescription: '{ count, capacity }',
  },
];

// ─── Register handlers ───

// Stub user service — only exposes interface enough to register routes
const stubUserService = {
  register: async () => { throw new Error('stub'); },
  login: async () => { throw new Error('stub'); },
  loginNoPassword: async () => { throw new Error('stub'); },
  getById: async () => null,
  update: async () => { throw new Error('stub'); },
  delete: async () => {},
  list: async () => [],
  validateToken: async () => null,
  clearLoginPolicy: async () => { throw new Error('stub'); },
  clearPublicKey: async () => { throw new Error('stub'); },
  getLoginInfo: async () => ({ exists: false, methods: [] as string[] }),
  refresh: async () => null,
};

const AUTH_PATHS = new Set(['/register', '/login']);

const stubStores = { metrics: { snapshot: () => ({ gets: 0, hits: 0, misses: 0, sets: 0, hitRate: 0 }) } };
collect('info', 'Info', '/', createInfoHandler(stubStores as any), () => true, infoRouteMeta);
collect('auth', 'Auth', '/api/users', createUserRouter(stubUserService as any), p => AUTH_PATHS.has(p), userRouteMeta);
collect('users', 'Users', '/api/users', createUserRouter(stubUserService as any), p => !AUTH_PATHS.has(p), userRouteMeta);
collect('audit', 'Audit', '/api/audit', createAuditRouter(new WorkersAuditLogger()), () => true, auditRouteMeta);

// ─── Generate .http files ───

const __dirname = dirname(fileURLToPath(import.meta.url));
const httpDir = resolve(__dirname, '..', 'http');
mkdirSync(httpDir, { recursive: true });

const fileTagOrder = ['info', 'auth', 'audit', 'users'];
const fileTagTitle: Record<string, string> = {
  info: 'Info',
  auth: 'Auth',
  audit: 'Audit',
  users: 'Users',
};

for (const ft of fileTagOrder) {
  const group = routes.filter(r => r.fileTag === ft);
  if (group.length === 0) continue;

  const hasVarId = group.some(r => r.path.includes(':id'));
  const lines: string[] = [
    `# HBI-AAD — ${fileTagTitle[ft]} Endpoints (auto-generated by scripts/export-http.ts)`,
    '',
    '@baseUrl = http://localhost:3000',
    ...(hasVarId ? ['@userId = 00000000-0000-0000-0000-000000000000'] : []),
    '',
  ];

  let currentTag = '';
  for (const route of group) {
    if (route.tag !== currentTag) {
      currentTag = route.tag;
      lines.push('');
      lines.push(`# ─── ${route.tag} ───`);
      lines.push('');
    }

    const { method, path, meta } = route;

    lines.push(`### ${method} ${path}${meta?.description ? ` — ${meta.description}` : ''}`);

    if (meta?.responseDescription) {
      lines.push(`# Response: ${meta.responseDescription}`);
    }

    const baseUrl = path.replace(/:id\b/g, '{{userId}}');
    if (meta?.queryExamples) {
      // Use the first example as the clickable URL; list others as comments
      const firstQs = new URLSearchParams(meta.queryExamples[0]).toString();
      lines.push(`${method} {{baseUrl}}${baseUrl}?${firstQs}`);
      for (let i = 1; i < meta.queryExamples.length; i++) {
        const qs = new URLSearchParams(meta.queryExamples[i]).toString();
        lines.push(`# ${method} {{baseUrl}}${baseUrl}?${qs}`);
      }
    } else {
      lines.push(`${method} {{baseUrl}}${baseUrl}`);
    }

    if (meta?.requestBody && !['GET', 'DELETE'].includes(method)) {
      lines.push('Content-Type: application/json');
      lines.push('');
      lines.push(JSON.stringify(meta.requestBody, null, 2));
    }

    lines.push('');
  }

  const content = lines.join('\n').replace(/\n{3,}/g, '\n\n');
  const fileName = resolve(httpDir, `${ft}.http`);
  writeFileSync(fileName, content, 'utf-8');
  console.log(`✓ Generated ${fileName} (${group.length} routes)`);
}
