// ─── Event type system ───

/**
 * A dispatchable event carrying a type discriminator and optional payload.
 * `id` and `timestamp` are auto-generated by {@link createEvent}.
 *
 * All fields are JSON-serialisable so they can cross HTTP boundaries
 * between external API callers and the Worker runtime.
 */
export interface Event<T = unknown> {
  readonly type: string;
  readonly payload?: T;
  readonly id: string;
  readonly timestamp: number;
  readonly metadata?: Record<string, unknown>;
}

/**
 * Public trigger input accepted from external HTTP API or from internal code.
 *
 * This is the "public contract" — external callers POST this shape
 * and internal code can emit the same shape via {@link IEventLoopControl.enqueueTrigger}.
 *
 * @example
 * ```json
 * // POST /api/events
 * { "type": "sandbox.create", "payload": { "name": "game-01", "cpu": 2 } }
 * ```
 */
export interface TriggerEventInput<T = unknown> {
  /** Event type discriminator (e.g. `"sandbox.create"`, `"dns.sync"`). */
  type: string;
  /** JSON-serialisable payload. */
  payload?: T;
  /** JSON-serialisable metadata (tracing, audit context, etc.). */
  metadata?: Record<string, unknown>;
}

export type EventHandler<T = unknown> = (event: Event<T>) => void | Promise<void>;

// ─── EventBus config ───

export interface EventBusConfig {
  /** Catch-all for handler exceptions. Defaults to rethrowing. */
  readonly onError?: (error: unknown, event: Event) => void;
}

// ─── EventLoop config & status (extend scheduler contracts) ───

import type { SchedulerConfig, SchedulerStatus } from '../scheduler/interfaces.ts';

export interface EventLoopConfig extends SchedulerConfig {
  /**
   * Maximum events processed per tick.
   * - `0` = drain all queued events in one tick.
   * - `1` = strict round-robin (one event per tick).
   */
  batchSize: number;
  /**
   * Maximum pending events allowed in the queue.
   * - `0` = unlimited.
   * - When exceeded, new events are rejected and {@link onError} is called.
   */
  maxQueueSize: number;
  /**
   * Error reporter for internal failures (persistence, dispatch, recover, etc.).
   * `context` describes where the error occurred (e.g. `"persist-enqueue"`).
   * When omitted, errors are silently dropped.
   */
  onError?: (error: unknown, context: string) => void;
}

export interface EventLoopStatus extends SchedulerStatus {
  queueSize: number;
  processedCount: number;
  config: EventLoopConfig;
}

export const DEFAULT_EVENT_LOOP_CONFIG: EventLoopConfig = {
  intervalMs: 60000,
  batchSize: 0,
  autoStart: false,
  maxQueueSize: 0,
};

// ─── Event factory ───

let _idCounter = 0;

/** Create an {@link Event} from a type discriminator and optional payload. */
export function createEvent<T>(type: string, payload?: T, metadata?: Record<string, unknown>): Event<T> {
  return {
    type,
    ...(payload !== undefined ? { payload } : {}),
    id: `evt_${Date.now().toString(36)}_${(_idCounter++).toString(36)}`,
    timestamp: Date.now(),
    ...(metadata !== undefined ? { metadata } : {}),
  } as Event<T>;
}

/**
 * Create an {@link Event} from a {@link TriggerEventInput}.
 * This is the bridge between external HTTP callers and the internal event system.
 */
export function eventFromTrigger<T>(input: TriggerEventInput<T>): Event<T> {
  if (!input.type || typeof input.type !== 'string') {
    throw new Error(`Invalid trigger: "type" must be a non-empty string, got ${typeof input.type}`);
  }
  return createEvent(input.type, input.payload, input.metadata);
}
