// Auto-generated by scripts/generate-instance-templates.mjs
// Do not edit manually. Run `npm run generate` to update.

export interface InstanceTemplateMeta {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
}

export interface InstanceTemplateDef {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  spec: Record<string, unknown>;
}

export const INSTANCE_TEMPLATES: InstanceTemplateDef[] = [
  {
    "id": "api-service",
    "name": "api-service",
    "description": "Node.js API 服务 — 环境变量注入，HTTP 健康检查，日志监控",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Container",
      "provider": "alibaba",
      "dependsOn": [
        "base-network"
      ],
      "containers": [
        {
          "name": "api",
          "image": "docker.io/library/node:20-alpine",
          "command": [
            "node",
            "server.js"
          ],
          "env": [
            {
              "name": "PORT",
              "value": "3000"
            },
            {
              "name": "NODE_ENV",
              "value": "production"
            }
          ],
          "ports": [
            {
              "containerPort": 3000,
              "protocol": "TCP"
            }
          ],
          "resources": {
            "limits": {
              "cpu": 2,
              "memory": 1024
            }
          },
          "livenessProbe": {
            "httpGet": {
              "port": 3000,
              "path": "/health"
            },
            "periodSeconds": 10
          },
          "providerOverrides": {
            "enableLogMonitor": true
          }
        }
      ]
    }
  },
  {
    "id": "base-network",
    "name": "base-network",
    "description": "基础网络层 — VPC + 安全组 + 子网，被其他服务模板继承",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Container",
      "provider": "alibaba",
      "region": "cn-hangzhou",
      "network": {
        "securityGroupId": "sg-bp1axxx",
        "subnetIds": [
          "vsw-bp1xxx"
        ],
        "allocatePublicIp": false
      },
      "restartPolicy": "Always",
      "providerOverrides": {
        "alibaba": {
          "instanceType": "ecs.g7.xlarge"
        }
      }
    }
  },
  {
    "id": "prod-stack",
    "name": "prod-stack",
    "description": "生产环境完整技术栈 — 合并 web + api + redis，带资源组保护和健康重试",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "ContainerGroup",
      "dependsOn": [
        "web-service",
        "api-service",
        "redis-cache"
      ],
      "containers": [
        {
          "name": "nginx",
          "env": [
            {
              "name": "UPSTREAM_API",
              "value": "api:3000"
            }
          ]
        },
        {
          "name": "api",
          "env": [
            {
              "name": "REDIS_URL",
              "value": "redis://redis:6379"
            },
            {
              "name": "DB_URL",
              "value": "placeholder://replace-me"
            }
          ]
        },
        {
          "name": "redis"
        }
      ],
      "extensions": {
        "healthMaxRetries": 3
      },
      "providerOverrides": {
        "alibaba": {
          "resourceGroupId": "rg-prod",
          "deletionProtection": true
        }
      }
    }
  },
  {
    "id": "redis-cache",
    "name": "redis-cache",
    "description": "Redis 7 缓存服务 — 无持久化，适合 session / 缓存场景",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Container",
      "provider": "alibaba",
      "region": "cn-hangzhou",
      "containers": [
        {
          "name": "redis",
          "image": "docker.io/library/redis:7-alpine",
          "command": [
            "redis-server",
            "--save",
            "",
            "--appendonly",
            "no"
          ],
          "resources": {
            "limits": {
              "cpu": 0.5,
              "memory": 512
            }
          },
          "ports": [
            {
              "containerPort": 6379,
              "protocol": "TCP"
            }
          ],
          "livenessProbe": {
            "tcpSocket": {
              "port": 6379
            },
            "periodSeconds": 10,
            "initialDelaySeconds": 5
          }
        }
      ],
      "network": {
        "allocatePublicIp": false
      },
      "restartPolicy": "Always"
    }
  },
  {
    "id": "sftp-server-podman",
    "name": "SFTP Server (Local)",
    "description": "Local Podman SFTP server for development/testing — mount local directories for file sharing. Configure SFTP_USERS env for user:pass:uid:gid:dirs.",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Container",
      "provider": "podman",
      "containers": [
        {
          "name": "sftp",
          "image": "docker.io/atmoz/sftp:alpine",
          "ports": [
            {
              "containerPort": 22,
              "protocol": "TCP"
            }
          ],
          "env": [
            {
              "name": "SFTP_USERS",
              "value": "dev:devpass:1000:1000:upload"
            }
          ],
          "resources": {
            "limits": {
              "cpu": 0.5,
              "memory": 256
            }
          },
          "livenessProbe": {
            "tcpSocket": {
              "port": 22
            },
            "periodSeconds": 30,
            "initialDelaySeconds": 10
          }
        }
      ],
      "network": {
        "allocatePublicIp": false,
        "mode": "private"
      },
      "restartPolicy": "Always"
    }
  },
  {
    "id": "sftp-server",
    "name": "SFTP Server",
    "description": "Secure file transfer server (SFTP/SSH) — mount volumes for persistent storage, per-user UID/GID, SSH key auth support. Based on atmoz/sftp OpenSSH server.",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Container",
      "region": "cn-hangzhou",
      "containers": [
        {
          "name": "sftp",
          "image": "registry.cn-hangzhou.aliyuncs.com/minecraft-graalvm/ftp_bp:latest",
          "ports": [
            {
              "containerPort": 22,
              "protocol": "TCP"
            }
          ],
          "env": [
            {
              "name": "SFTP_USERS",
              "value": "sftpuser:changeme:::upload"
            }
          ],
          "resources": {
            "limits": {
              "cpu": 2,
              "memory": 2048
            }
          },
          "livenessProbe": {
            "tcpSocket": {
              "port": 22
            },
            "periodSeconds": 30,
            "initialDelaySeconds": 10
          },
          "readinessProbe": {
            "tcpSocket": {
              "port": 22
            },
            "periodSeconds": 10,
            "initialDelaySeconds": 5
          }
        }
      ],
      "extensions": {
        "healthMaxRetries": 3
      },
      "network": {
        "mode": "vpc",
        "publicIp": {
          "allocate": true,
          "bandwidth": 10
        },
        "vpc": {
          "securityGroupId": "sg-bp16o5urk39itwcqmdzj",
          "subnetIds": [
            "vsw-bp1xx36ys1jou7o1bsdpp",
            "vsw-bp1grwzlgy2739dxnskbz",
            "vsw-bp1rv5m61jx4kmld0cc12",
            "vsw-bp1wfyusfye82wm3d3zew"
          ]
        }
      },
      "restartPolicy": "Always"
    }
  },
  {
    "id": "vsftp-pub",
    "name": "vsftp_pub",
    "description": "VSFTP public access with EIP — spot instance, auto public IP, multi-zone",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Container",
      "region": "cn-hangzhou",
      "containers": [
        {
          "name": "vsftp",
          "image": "registry-vpc.cn-hangzhou.aliyuncs.com/minecraft-graalvm/ftp_bp:latest",
          "ports": [
            {
              "containerPort": 22,
              "protocol": "TCP"
            }
          ],
          "env": [
            {
              "name": "SFTP_USERS",
              "value": "test:test123:::upload"
            }
          ],
          "resources": {
            "limits": {
              "cpu": 2,
              "memory": 2048
            }
          },
          "livenessProbe": {
            "tcpSocket": {
              "port": 22
            },
            "periodSeconds": 30,
            "initialDelaySeconds": 10
          },
          "imagePullPolicy": "Always",
          "stdin": true,
          "tty": true
        }
      ],
      "extensions": {
        "spotStrategy": "SpotAsPriceGo",
        "healthMaxRetries": 3,
        "providerOverrides": {
          "alibaba": {
            "ingressBandwidth": 100,
            "egressBandwidth": 100,
            "autoCreateEip": true,
            "eipBandwidth": 19,
            "autoMatchImageCache": true
          }
        }
      },
      "network": {
        "mode": "vpc",
        "publicIp": {
          "allocate": true,
          "bandwidth": 19
        },
        "vpc": {
          "securityGroupId": "sg-bp16o5urk39itwcqmdzj",
          "subnetIds": [
            "vsw-bp1xx36ys1jou7o1bsdpp",
            "vsw-bp1grwzlgy2739dxnskbz",
            "vsw-bp1rv5m61jx4kmld0cc12",
            "vsw-bp1wfyusfye82wm3d3zew"
          ]
        }
      },
      "restartPolicy": "Always"
    }
  },
  {
    "id": "web-service",
    "name": "web-service",
    "description": "Nginx Web 服务 — 公网可达，HTTP 健康检查，支持 EIP 带宽配置",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Container",
      "provider": "alibaba",
      "dependsOn": [
        "base-network"
      ],
      "containers": [
        {
          "name": "nginx",
          "image": "docker.io/library/nginx:alpine",
          "ports": [
            {
              "containerPort": 80,
              "protocol": "TCP"
            },
            {
              "containerPort": 443,
              "protocol": "TCP"
            }
          ],
          "resources": {
            "limits": {
              "cpu": 1,
              "memory": 256
            }
          },
          "livenessProbe": {
            "httpGet": {
              "port": 80,
              "path": "/health"
            },
            "periodSeconds": 15,
            "initialDelaySeconds": 10
          },
          "readinessProbe": {
            "httpGet": {
              "port": 80,
              "path": "/health"
            },
            "periodSeconds": 5
          },
          "providerOverrides": {
            "eipBandwidth": 50
          }
        }
      ],
      "network": {
        "allocatePublicIp": true,
        "publicIpBandwidth": 50
      },
      "providerOverrides": {
        "alibaba": {
          "spotStrategy": "SpotAsPriceGo"
        }
      }
    }
  }
];

export const INSTANCE_TEMPLATE_METAS: InstanceTemplateMeta[] = [
  {
    "id": "api-service",
    "name": "api-service",
    "description": "Node.js API 服务 — 环境变量注入，HTTP 健康检查，日志监控",
    "category": "",
    "tags": []
  },
  {
    "id": "base-network",
    "name": "base-network",
    "description": "基础网络层 — VPC + 安全组 + 子网，被其他服务模板继承",
    "category": "",
    "tags": []
  },
  {
    "id": "prod-stack",
    "name": "prod-stack",
    "description": "生产环境完整技术栈 — 合并 web + api + redis，带资源组保护和健康重试",
    "category": "",
    "tags": []
  },
  {
    "id": "redis-cache",
    "name": "redis-cache",
    "description": "Redis 7 缓存服务 — 无持久化，适合 session / 缓存场景",
    "category": "",
    "tags": []
  },
  {
    "id": "sftp-server-podman",
    "name": "SFTP Server (Local)",
    "description": "Local Podman SFTP server for development/testing — mount local directories for file sharing. Configure SFTP_USERS env for user:pass:uid:gid:dirs.",
    "category": "",
    "tags": []
  },
  {
    "id": "sftp-server",
    "name": "SFTP Server",
    "description": "Secure file transfer server (SFTP/SSH) — mount volumes for persistent storage, per-user UID/GID, SSH key auth support. Based on atmoz/sftp OpenSSH server.",
    "category": "",
    "tags": []
  },
  {
    "id": "vsftp-pub",
    "name": "vsftp_pub",
    "description": "VSFTP public access with EIP — spot instance, auto public IP, multi-zone",
    "category": "",
    "tags": []
  },
  {
    "id": "web-service",
    "name": "web-service",
    "description": "Nginx Web 服务 — 公网可达，HTTP 健康检查，支持 EIP 带宽配置",
    "category": "",
    "tags": []
  }
];
