// Auto-generated by scripts/generate-instance-templates.mjs
// Do not edit manually. Run `npm run generate` to update.

export interface InstanceTemplateMeta {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
}

export interface InstanceTemplateDef {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  spec: Record<string, unknown>;
}

export const INSTANCE_TEMPLATES: InstanceTemplateDef[] = [
  {
    "id": "api-service",
    "name": "api-service",
    "description": "Node.js API 服务 — 环境变量注入，HTTP 健康检查，日志监控",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "dependsOn": [
        "base-network"
      ],
      "spec": {
        "metadata": {
          "name": "api-service"
        },
        "spec": {
          "containers": [
            {
              "name": "api",
              "image": "docker.io/library/node:20-alpine",
              "command": [
                "node",
                "server.js"
              ],
              "env": [
                {
                  "name": "PORT",
                  "value": "3000"
                },
                {
                  "name": "NODE_ENV",
                  "value": "production"
                }
              ],
              "ports": [
                {
                  "containerPort": 3000,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 2,
                  "memory": 1024
                }
              },
              "livenessProbe": {
                "httpGet": {
                  "port": 3000,
                  "path": "/health"
                },
                "periodSeconds": 10
              },
              "providerOverrides": {
                "enableLogMonitor": true
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "base-alpine",
    "name": "base-alpine",
    "description": "Base Alpine Linux — minimal OS layer, 256MB RAM, sleep 3600",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "base-alpine"
        },
        "spec": {
          "containers": [
            {
              "name": "alpine",
              "image": "docker.io/library/alpine:latest",
              "command": [
                "sleep",
                "3600"
              ],
              "resources": {
                "limits": {
                  "cpu": 0.25,
                  "memory": 256
                }
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "base-network",
    "name": "base-network",
    "description": "基础网络层 — VPC + 安全组 + 子网，被其他服务模板继承",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "base-network"
        },
        "spec": {
          "containers": [],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou",
            "securityGroupId": "sg-bp1axxx",
            "subnetIds": [
              "vsw-bp1xxx"
            ],
            "instanceType": "ecs.g7.xlarge"
          }
        }
      }
    }
  },
  {
    "id": "custom-alpine",
    "name": "custom-alpine",
    "description": "Custom Alpine — inherits base-alpine, adds curl + env vars",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "dependsOn": [
        "base-alpine"
      ],
      "spec": {
        "metadata": {
          "name": "custom-alpine"
        },
        "spec": {
          "containers": [
            {
              "name": "alpine",
              "command": [
                "sh",
                "-c",
                "while true; do echo \"Hello from DAG\"; curl -s http://localhost/health 2>/dev/null || echo \"nginx not ready\"; sleep 10; done"
              ],
              "env": [
                {
                  "name": "APP_ENV",
                  "value": "development"
                },
                {
                  "name": "LOG_LEVEL",
                  "value": "debug"
                }
              ]
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "demo-pod",
    "name": "demo-pod",
    "description": "Pod — nginx + alpine 共享网络",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "demo-pod"
        },
        "spec": {
          "containers": [
            {
              "name": "demo-pod-web",
              "image": "docker.io/library/nginx:latest",
              "command": [
                "nginx",
                "-g",
                "daemon off;"
              ],
              "ports": [
                {
                  "containerPort": 80,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 128
                }
              }
            },
            {
              "name": "demo-pod-sidecar",
              "image": "docker.io/library/alpine:latest",
              "command": [
                "sh",
                "-c",
                "while true; do echo \"sidecar alive\"; sleep 30; done"
              ],
              "resources": {
                "limits": {
                  "cpu": 0.25,
                  "memory": 64
                }
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "fedora",
    "name": "fedora",
    "description": "Fedora Linux — minimal OS layer, 256MB RAM, sleep 3600",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "fedora"
        },
        "spec": {
          "containers": [
            {
              "name": "fedora",
              "image": "registry.fedoraproject.org/fedora:latest",
              "command": [
                "sleep",
                "3600"
              ],
              "resources": {
                "limits": {
                  "cpu": 0.25,
                  "memory": 256
                }
              },
              "livenessProbe": {
                "exec": {
                  "command": [
                    "sh",
                    "-c",
                    "kill -0 1"
                  ]
                },
                "periodSeconds": 15,
                "initialDelaySeconds": 5,
                "failureThreshold": 3
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "full-stack",
    "name": "full-stack",
    "description": "Full stack — merges custom-alpine + nginx with app container",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "dependsOn": [
        "custom-alpine",
        "nginx"
      ],
      "spec": {
        "metadata": {
          "name": "full-stack"
        },
        "spec": {
          "containers": [
            {
              "name": "alpine",
              "env": [
                {
                  "name": "NGINX_HOST",
                  "value": "localhost"
                },
                {
                  "name": "DB_URL",
                  "value": "sqlite:///data/app.db"
                }
              ]
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local",
            "autoCreateEip": true
          }
        }
      }
    }
  },
  {
    "id": "gpu-compute",
    "name": "gpu-compute",
    "description": "GPU compute instance — NVIDIA CUDA 12.0 runtime, T4 GPU, spot instance",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "gpu-compute"
        },
        "spec": {
          "containers": [
            {
              "name": "gpu-worker",
              "image": "docker.io/nvidia/cuda:12.0-runtime-ubuntu22.04",
              "command": [
                "nvidia-smi"
              ],
              "ports": [
                {
                  "containerPort": 8888,
                  "protocol": "TCP"
                }
              ],
              "env": [
                {
                  "name": "NVIDIA_VISIBLE_DEVICES",
                  "value": "all"
                },
                {
                  "name": "CUDA_VISIBLE_DEVICES",
                  "value": "0"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 8,
                  "memory": 32768,
                  "gpu": 1,
                  "gpuType": "nvidia.com/gpu"
                }
              },
              "livenessProbe": {
                "tcpSocket": {
                  "port": 8888
                },
                "periodSeconds": 30,
                "initialDelaySeconds": 60
              },
              "readinessProbe": {
                "exec": {
                  "command": [
                    "nvidia-smi"
                  ]
                },
                "periodSeconds": 30,
                "initialDelaySeconds": 30
              },
              "imagePullPolicy": "IfNotPresent",
              "stdin": true,
              "tty": true
            }
          ],
          "restartPolicy": "OnFailure"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou",
            "securityGroupId": "sg-bp16o5urk39itwcqmdzj",
            "subnetIds": [
              "vsw-bp1xx36ys1jou7o1bsdpp",
              "vsw-bp1grwzlgy2739dxnskbz",
              "vsw-bp1rv5m61jx4kmld0cc12",
              "vsw-bp1wfyusfye82wm3d3zew"
            ],
            "spotStrategy": "SpotAsPriceGo",
            "instanceType": "ecs.gn6v-c8g1.2xlarge",
            "ingressBandwidth": 100,
            "egressBandwidth": 100,
            "autoCreateEip": true,
            "eipBandwidth": 50,
            "autoMatchImageCache": true,
            "cpuArchitecture": "AMD64",
            "healthMaxRetries": 3
          }
        }
      }
    }
  },
  {
    "id": "gpu-inference",
    "name": "gpu-inference",
    "description": "GPU inference server — requires NVIDIA GPU (nvidia.com/gpu)",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "gpu-inference"
        },
        "spec": {
          "containers": [
            {
              "name": "inference",
              "image": "docker.io/nvidia/cuda:12.2-runtime",
              "command": [
                "python",
                "-m",
                "my_inference_server"
              ],
              "ports": [
                {
                  "containerPort": 8080,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 4,
                  "memory": 8192,
                  "gpu": 1
                }
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local",
            "autoCreateEip": true
          }
        }
      }
    }
  },
  {
    "id": "lifecycle-busybox",
    "name": "lifecycle-busybox",
    "description": "全生命周期验证 (busybox) — 纯公开镜像，无需推送，开箱即用",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "lifecycle-bb"
        },
        "spec": {
          "containers": [
            {
              "name": "lifecycle-bb-consumer",
              "image": "busybox:latest",
              "command": [
                "sh",
                "-c",
                "nc -l -p 9999 | while read line; do echo \"$line\" >> /tmp/received.txt; done"
              ],
              "ports": [
                {
                  "containerPort": 9999,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 0.25,
                  "memory": 128
                }
              }
            },
            {
              "name": "lifecycle-bb-producer",
              "image": "busybox:latest",
              "command": [
                "sh",
                "-c",
                "SEQ=0; while true; do SEQ=$((SEQ+1)); echo \"{\\\"seq\\\":$SEQ,\\\"ts\\\":$(date +%s)}\" | nc -w 1 localhost 9999; echo \"[producer] seq=$SEQ\"; sleep 1; done"
              ],
              "resources": {
                "limits": {
                  "cpu": 0.25,
                  "memory": 128
                }
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou"
          }
        }
      }
    }
  },
  {
    "id": "lifecycle-test",
    "name": "lifecycle-test",
    "description": "全生命周期验证 — Producer/Consumer 双容器 localhost:9999 TCP 通信，验证 11 态状态机、重启、更新、删除、GC",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "lifecycle-test"
        },
        "spec": {
          "containers": [
            {
              "name": "lifecycle-test-consumer",
              "image": "registry-vpc.cn-hangzhou.aliyuncs.com/minecraft-graalvm/ocibox:latest",
              "command": [
                "/usr/local/bin/consumer"
              ],
              "ports": [
                {
                  "containerPort": 9999,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 256
                }
              }
            },
            {
              "name": "lifecycle-test-producer",
              "image": "registry-vpc.cn-hangzhou.aliyuncs.com/minecraft-graalvm/ocibox:latest",
              "command": [
                "/usr/local/bin/producer",
                "1"
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 256
                }
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou"
          }
        }
      }
    }
  },
  {
    "id": "minio-server",
    "name": "minio-server",
    "description": "MinIO S3-compatible object storage — ports 9000 (API) / 9001 (console)",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "singleton": true,
      "spec": {
        "metadata": {
          "name": "minio-server"
        },
        "spec": {
          "containers": [
            {
              "name": "minio",
              "image": "quay.io/minio/minio:latest",
              "command": [
                "server",
                "/data",
                "--console-address",
                ":9001"
              ],
              "ports": [
                {
                  "containerPort": 9000,
                  "protocol": "TCP"
                },
                {
                  "containerPort": 9001,
                  "protocol": "TCP"
                }
              ],
              "env": [
                {
                  "name": "MINIO_ROOT_USER",
                  "value": "minioadmin"
                },
                {
                  "name": "MINIO_ROOT_PASSWORD",
                  "value": "minioadmin"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 512
                }
              },
              "readinessProbe": {
                "tcpSocket": {
                  "port": 9000
                },
                "periodSeconds": 5,
                "initialDelaySeconds": 5
              }
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local",
            "autoCreateEip": true
          }
        }
      }
    }
  },
  {
    "id": "nginx-arg",
    "name": "nginx-arg",
    "description": "Nginx with explicit command+args — 验证模板参数穿透到容器",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "singleton": true,
      "spec": {
        "metadata": {
          "name": "nginx-arg"
        },
        "spec": {
          "containers": [
            {
              "name": "nginx-arg",
              "image": "docker.io/library/nginx:latest",
              "command": [
                "nginx"
              ],
              "args": [
                "-g",
                "daemon off;"
              ],
              "ports": [
                {
                  "containerPort": 80,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 128
                }
              },
              "livenessProbe": {
                "httpGet": {
                  "path": "/",
                  "port": 80
                },
                "periodSeconds": 10,
                "initialDelaySeconds": 5
              }
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "nginx",
    "name": "nginx",
    "description": "Nginx web server — ports 80, readiness check, singleton",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "singleton": true,
      "spec": {
        "metadata": {
          "name": "nginx"
        },
        "spec": {
          "containers": [
            {
              "name": "nginx",
              "image": "docker.io/library/nginx:latest",
              "command": [
                "nginx"
              ],
              "args": [
                "-g",
                "daemon off;"
              ],
              "ports": [
                {
                  "containerPort": 80,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 128
                }
              },
              "livenessProbe": {
                "httpGet": {
                  "path": "/",
                  "port": 80
                },
                "periodSeconds": 10,
                "initialDelaySeconds": 5
              },
              "readinessProbe": {
                "tcpSocket": {
                  "port": 80
                },
                "periodSeconds": 5,
                "initialDelaySeconds": 2
              }
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "prod-stack",
    "name": "prod-stack",
    "description": "生产环境完整技术栈 — 合并 web + api + redis，带资源组保护和健康重试",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "dependsOn": [
        "web-service",
        "api-service",
        "redis-cache"
      ],
      "spec": {
        "metadata": {
          "name": "prod-stack"
        },
        "spec": {
          "containers": [
            {
              "name": "nginx",
              "env": [
                {
                  "name": "UPSTREAM_API",
                  "value": "api:3000"
                }
              ]
            },
            {
              "name": "api",
              "env": [
                {
                  "name": "REDIS_URL",
                  "value": "redis://redis:6379"
                },
                {
                  "name": "DB_URL",
                  "value": "placeholder://replace-me"
                }
              ]
            },
            {
              "name": "redis"
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "healthMaxRetries": 3,
            "resourceGroupId": "rg-prod",
            "deletionProtection": true
          }
        }
      }
    }
  },
  {
    "id": "redis-cache",
    "name": "redis-cache",
    "description": "Redis 7 缓存服务 — 无持久化，适合 session / 缓存场景",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "redis-cache"
        },
        "spec": {
          "containers": [
            {
              "name": "redis",
              "image": "docker.io/library/redis:7-alpine",
              "command": [
                "redis-server",
                "--save",
                "",
                "--appendonly",
                "no"
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 512
                }
              },
              "ports": [
                {
                  "containerPort": 6379,
                  "protocol": "TCP"
                }
              ],
              "livenessProbe": {
                "tcpSocket": {
                  "port": 6379
                },
                "periodSeconds": 10,
                "initialDelaySeconds": 5
              }
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou"
          }
        }
      }
    }
  },
  {
    "id": "sftp-server-podman",
    "name": "SFTP Server (Local)",
    "description": "Local Podman SFTP server for development/testing — mount local directories for file sharing. Configure SFTP_USERS env for user:pass:uid:gid:dirs.",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "SFTP Server (Local)"
        },
        "spec": {
          "containers": [
            {
              "name": "sftp",
              "image": "docker.io/atmoz/sftp:alpine",
              "ports": [
                {
                  "containerPort": 22,
                  "protocol": "TCP"
                }
              ],
              "env": [
                {
                  "name": "SFTP_USERS",
                  "value": "dev:devpass:1000:1000:upload"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 0.5,
                  "memory": 256
                }
              },
              "livenessProbe": {
                "tcpSocket": {
                  "port": 22
                },
                "periodSeconds": 30,
                "initialDelaySeconds": 10
              }
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local"
          }
        }
      }
    }
  },
  {
    "id": "sftp-server",
    "name": "SFTP Server",
    "description": "Secure file transfer server (SFTP/SSH) — mount volumes for persistent storage, per-user UID/GID, SSH key auth support. Based on atmoz/sftp OpenSSH server.",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "SFTP Server"
        },
        "spec": {
          "containers": [
            {
              "name": "sftp",
              "image": "registry.cn-hangzhou.aliyuncs.com/minecraft-graalvm/ftp_bp:latest",
              "ports": [
                {
                  "containerPort": 22,
                  "protocol": "TCP"
                }
              ],
              "env": [
                {
                  "name": "SFTP_USERS",
                  "value": "sftpuser:changeme:::upload"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 2,
                  "memory": 2048
                }
              },
              "livenessProbe": {
                "tcpSocket": {
                  "port": 22
                },
                "periodSeconds": 30,
                "initialDelaySeconds": 10
              },
              "readinessProbe": {
                "tcpSocket": {
                  "port": 22
                },
                "periodSeconds": 10,
                "initialDelaySeconds": 5
              }
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou",
            "healthMaxRetries": 3,
            "autoCreateEip": true,
            "eipBandwidth": 10,
            "securityGroupId": "sg-bp16o5urk39itwcqmdzj",
            "subnetIds": [
              "vsw-bp1xx36ys1jou7o1bsdpp",
              "vsw-bp1grwzlgy2739dxnskbz",
              "vsw-bp1rv5m61jx4kmld0cc12",
              "vsw-bp1wfyusfye82wm3d3zew"
            ]
          }
        }
      }
    }
  },
  {
    "id": "vsftp-pub",
    "name": "vsftp_pub",
    "description": "VSFTP public access with EIP — spot instance, auto public IP, multi-zone",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "vsftp_pub"
        },
        "spec": {
          "containers": [
            {
              "name": "vsftp",
              "image": "registry-vpc.cn-hangzhou.aliyuncs.com/minecraft-graalvm/ftp_bp:latest",
              "ports": [
                {
                  "containerPort": 22,
                  "protocol": "TCP"
                }
              ],
              "env": [
                {
                  "name": "SFTP_USERS",
                  "value": "test:test123:::upload"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 2,
                  "memory": 2048
                }
              },
              "livenessProbe": {
                "tcpSocket": {
                  "port": 22
                },
                "periodSeconds": 30,
                "initialDelaySeconds": 10
              },
              "imagePullPolicy": "Always",
              "stdin": true,
              "tty": true
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou",
            "securityGroupId": "sg-bp16o5urk39itwcqmdzj",
            "subnetIds": [
              "vsw-bp1xx36ys1jou7o1bsdpp",
              "vsw-bp1grwzlgy2739dxnskbz",
              "vsw-bp1rv5m61jx4kmld0cc12",
              "vsw-bp1wfyusfye82wm3d3zew"
            ],
            "healthMaxRetries": 3,
            "spotStrategy": "SpotAsPriceGo",
            "ingressBandwidth": 100,
            "egressBandwidth": 100,
            "autoCreateEip": true,
            "eipBandwidth": 19,
            "autoMatchImageCache": true
          }
        }
      }
    }
  },
  {
    "id": "vsftp_GPU",
    "name": "vsftp_GPU",
    "description": "VSFTP with GPU acceleration — T4 GPU (ecs.gn6v), spot instance, auto EIP, multi-zone",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "spec": {
        "metadata": {
          "name": "vsftp_GPU"
        },
        "spec": {
          "containers": [
            {
              "name": "vsftp",
              "image": "registry-vpc.cn-hangzhou.aliyuncs.com/minecraft-graalvm/ftp_bp:latest",
              "ports": [
                {
                  "containerPort": 22,
                  "protocol": "TCP"
                }
              ],
              "env": [
                {
                  "name": "SFTP_USERS",
                  "value": "test:test123:::upload"
                },
                {
                  "name": "NVIDIA_VISIBLE_DEVICES",
                  "value": "all"
                },
                {
                  "name": "CUDA_VISIBLE_DEVICES",
                  "value": "0"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 8,
                  "memory": 32768,
                  "gpu": 1,
                  "gpuType": "nvidia.com/gpu"
                }
              },
              "livenessProbe": {
                "tcpSocket": {
                  "port": 22
                },
                "periodSeconds": 30,
                "initialDelaySeconds": 10
              },
              "imagePullPolicy": "Always",
              "stdin": true,
              "tty": true
            }
          ],
          "restartPolicy": "Always"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "cn-hangzhou",
            "securityGroupId": "sg-bp16o5urk39itwcqmdzj",
            "subnetIds": [
              "vsw-bp1xx36ys1jou7o1bsdpp",
              "vsw-bp1grwzlgy2739dxnskbz",
              "vsw-bp1rv5m61jx4kmld0cc12",
              "vsw-bp1wfyusfye82wm3d3zew"
            ],
            "healthMaxRetries": 3,
            "spotStrategy": "SpotAsPriceGo",
            "instanceType": "ecs.gn6v-c8g1.2xlarge",
            "ingressBandwidth": 100,
            "egressBandwidth": 100,
            "autoCreateEip": true,
            "eipBandwidth": 19,
            "autoMatchImageCache": true,
            "cpuArchitecture": "AMD64"
          }
        }
      }
    }
  },
  {
    "id": "web-service",
    "name": "web-service",
    "description": "Nginx Web 服务 — 公网可达，HTTP 健康检查，支持 EIP 带宽配置",
    "category": "",
    "tags": [],
    "spec": {
      "apiVersion": "hbi-aad/v1",
      "kind": "Pod",
      "dependsOn": [
        "base-network"
      ],
      "spec": {
        "metadata": {
          "name": "web-service"
        },
        "spec": {
          "containers": [
            {
              "name": "nginx",
              "image": "docker.io/library/nginx:alpine",
              "ports": [
                {
                  "containerPort": 80,
                  "protocol": "TCP"
                },
                {
                  "containerPort": 443,
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "limits": {
                  "cpu": 1,
                  "memory": 256
                }
              },
              "livenessProbe": {
                "httpGet": {
                  "port": 80,
                  "path": "/health"
                },
                "periodSeconds": 15,
                "initialDelaySeconds": 10
              },
              "readinessProbe": {
                "httpGet": {
                  "port": 80,
                  "path": "/health"
                },
                "periodSeconds": 5
              }
            }
          ],
          "restartPolicy": "Never"
        },
        "providerOverrides": {
          "alibaba": {
            "region": "local",
            "autoCreateEip": true,
            "eipBandwidth": 50,
            "spotStrategy": "SpotAsPriceGo"
          }
        }
      }
    }
  }
];

export const INSTANCE_TEMPLATE_METAS: InstanceTemplateMeta[] = [
  {
    "id": "api-service",
    "name": "api-service",
    "description": "Node.js API 服务 — 环境变量注入，HTTP 健康检查，日志监控",
    "category": "",
    "tags": []
  },
  {
    "id": "base-alpine",
    "name": "base-alpine",
    "description": "Base Alpine Linux — minimal OS layer, 256MB RAM, sleep 3600",
    "category": "",
    "tags": []
  },
  {
    "id": "base-network",
    "name": "base-network",
    "description": "基础网络层 — VPC + 安全组 + 子网，被其他服务模板继承",
    "category": "",
    "tags": []
  },
  {
    "id": "custom-alpine",
    "name": "custom-alpine",
    "description": "Custom Alpine — inherits base-alpine, adds curl + env vars",
    "category": "",
    "tags": []
  },
  {
    "id": "demo-pod",
    "name": "demo-pod",
    "description": "Pod — nginx + alpine 共享网络",
    "category": "",
    "tags": []
  },
  {
    "id": "fedora",
    "name": "fedora",
    "description": "Fedora Linux — minimal OS layer, 256MB RAM, sleep 3600",
    "category": "",
    "tags": []
  },
  {
    "id": "full-stack",
    "name": "full-stack",
    "description": "Full stack — merges custom-alpine + nginx with app container",
    "category": "",
    "tags": []
  },
  {
    "id": "gpu-compute",
    "name": "gpu-compute",
    "description": "GPU compute instance — NVIDIA CUDA 12.0 runtime, T4 GPU, spot instance",
    "category": "",
    "tags": []
  },
  {
    "id": "gpu-inference",
    "name": "gpu-inference",
    "description": "GPU inference server — requires NVIDIA GPU (nvidia.com/gpu)",
    "category": "",
    "tags": []
  },
  {
    "id": "lifecycle-busybox",
    "name": "lifecycle-busybox",
    "description": "全生命周期验证 (busybox) — 纯公开镜像，无需推送，开箱即用",
    "category": "",
    "tags": []
  },
  {
    "id": "lifecycle-test",
    "name": "lifecycle-test",
    "description": "全生命周期验证 — Producer/Consumer 双容器 localhost:9999 TCP 通信，验证 11 态状态机、重启、更新、删除、GC",
    "category": "",
    "tags": []
  },
  {
    "id": "minio-server",
    "name": "minio-server",
    "description": "MinIO S3-compatible object storage — ports 9000 (API) / 9001 (console)",
    "category": "",
    "tags": []
  },
  {
    "id": "nginx-arg",
    "name": "nginx-arg",
    "description": "Nginx with explicit command+args — 验证模板参数穿透到容器",
    "category": "",
    "tags": []
  },
  {
    "id": "nginx",
    "name": "nginx",
    "description": "Nginx web server — ports 80, readiness check, singleton",
    "category": "",
    "tags": []
  },
  {
    "id": "prod-stack",
    "name": "prod-stack",
    "description": "生产环境完整技术栈 — 合并 web + api + redis，带资源组保护和健康重试",
    "category": "",
    "tags": []
  },
  {
    "id": "redis-cache",
    "name": "redis-cache",
    "description": "Redis 7 缓存服务 — 无持久化，适合 session / 缓存场景",
    "category": "",
    "tags": []
  },
  {
    "id": "sftp-server-podman",
    "name": "SFTP Server (Local)",
    "description": "Local Podman SFTP server for development/testing — mount local directories for file sharing. Configure SFTP_USERS env for user:pass:uid:gid:dirs.",
    "category": "",
    "tags": []
  },
  {
    "id": "sftp-server",
    "name": "SFTP Server",
    "description": "Secure file transfer server (SFTP/SSH) — mount volumes for persistent storage, per-user UID/GID, SSH key auth support. Based on atmoz/sftp OpenSSH server.",
    "category": "",
    "tags": []
  },
  {
    "id": "vsftp-pub",
    "name": "vsftp_pub",
    "description": "VSFTP public access with EIP — spot instance, auto public IP, multi-zone",
    "category": "",
    "tags": []
  },
  {
    "id": "vsftp_GPU",
    "name": "vsftp_GPU",
    "description": "VSFTP with GPU acceleration — T4 GPU (ecs.gn6v), spot instance, auto EIP, multi-zone",
    "category": "",
    "tags": []
  },
  {
    "id": "web-service",
    "name": "web-service",
    "description": "Nginx Web 服务 — 公网可达，HTTP 健康检查，支持 EIP 带宽配置",
    "category": "",
    "tags": []
  }
];
